# Generated by Django 2.0 on 2020-04-27 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_customer_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customer',
        ),
    ]
